#pragma checksum "D:\demo\test01\spark\ui\Spark.UI\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2174260CF483372D67BD27D2B47A752474334A45D5B0CBDD5D2597355F2D8FCD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.UI
{
    partial class App : global::Microsoft.UI.Xaml.Application
    {
    }
}

