#pragma checksum "D:\demo\test01\spark\ui\Spark.UI\MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "371984DCA045079E0D8AB821C25C9EC9C3E4BB3B8022AD51789539DAC284612B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.UI
{
    partial class MainWindow : global::Microsoft.UI.Xaml.Window
    {


#pragma warning disable 0169    //  Proactively suppress unused/uninitialized field warning in case they aren't used, for things like x:Name
#pragma warning disable 0649
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid Root; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid ContentClip; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid MainPanel; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid SettingsPanel; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid FavGroupPanel; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid FavConfirmPanel; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Border FavConfirmCard; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform FavConfirmCardShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.ScaleTransform FavConfirmCardScale; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock FavConfirmMsg; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button FavConfirmCancelBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Border FavGroupCard; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform FavGroupCardShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.ScaleTransform FavGroupCardScale; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBox FavGroupName; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform SetShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.ScaleTransform SetScale; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel PaneGeneral; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel PaneAppearance; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel PaneBuiltins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel PanePlugins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel PaneAbout; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform PaneAboutShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock AboutUpdateStatus; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ProgressBar UpdateProgress; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnCheckUpdate; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnOpenRelease; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock CheckUpdateLabel; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock AboutVersionText; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform PanePluginsShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel SubPaneInstalledPlugins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel SubPanePluginSecurity; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel SubPaneMarketplace; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform SubPaneMarketplaceShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid MarketFilterRow; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Border MarketUpdateNotice; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ScrollViewer MarketTagScroll; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel MarketLoadingWrap; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock MarketStatusText; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid MarketEmpty; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock MarketFilterEmpty; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ListView MarketList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ItemsControl MarketTagBar; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button MarketUpdateAllBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock MarketUpdateNoticeText; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBox MarketFilterBox; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ComboBox MarketFilterCombo; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel MarketCustomReposPanel; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Border MarketCustomWarning; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ItemsControl MarketCustomUrlList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ComboBox MarketSourceCombo; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button MarketCustomManageBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button MarketRefreshBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform SubPanePluginSecurityShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ItemsControl TrustedDevList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock TrustedDevStatus; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBox TrustedDevKeyId; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBox TrustedDevPubkey; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton StrictModeSwitch; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform SubPaneInstalledPluginsShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock PluginStatus; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid PluginEmpty; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ListView PluginList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid ChangePluginDirWrap; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button ChangePluginDirBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock PluginDirText; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid DevLoadPluginWrap; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button DevLoadPluginBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button TabInstalledPluginsBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button TabPluginSecurityBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button TabMarketplaceBtn; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform PaneBuiltinsShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBox BuiltinFilterBox; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ListView BuiltinList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock BuiltinFilterEmpty; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform PaneAppearanceShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ComboBox ViewCombo; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ComboBox ThemeCombo; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform PaneGeneralShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton DevModeSwitch; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton BallSwitch; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnHotkeyAlt; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnHotkeyCtrl; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton StartupSwitch; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button NavGeneral; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button NavAppearance; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button NavBuiltins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button NavPlugins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button NavAbout; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.FontIcon NavIconAbout; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.FontIcon NavIconPlugins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.FontIcon NavIconBuiltins; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.FontIcon NavIconAppearance; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.FontIcon NavIconGeneral; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform MainShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.ScaleTransform MainScale; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ListView ResultList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.GridView ResultGrid; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock EmptyState; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Grid FooterBar; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock Footer; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel FavRoot; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Border FavBodyClip; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.RectangleGeometry FavBodyClipRect; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ScrollViewer FavBody; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel FavItems; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform FavItemsShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.ColumnDefinition FavGroupsCol; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button FavToggle; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button FavAddGroup; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.StackPanel FavGroups; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Shapes.Path FavChevronPath; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock FavCount; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.TranslateTransform FavChevronShift; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Media.RotateTransform FavChevronRotate; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBox QueryBox; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.TextBlock SearchMeta; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnSettings; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnViewList; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private global::Microsoft.UI.Xaml.Controls.Button BtnViewGrid; 
#pragma warning restore 0649
#pragma warning restore 0169
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        private bool _contentLoaded;

        /// <summary>
        /// InitializeComponent()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent()
        {
            if (_contentLoaded)
                return;

            _contentLoaded = true;

            global::System.Uri resourceLocator = new global::System.Uri("ms-appx:///MainWindow.xaml");
            global::Microsoft.UI.Xaml.Application.LoadComponent(this, resourceLocator, global::Microsoft.UI.Xaml.Controls.Primitives.ComponentResourceLocation.Application);
        }

        partial void UnloadObject(global::Microsoft.UI.Xaml.DependencyObject unloadableObject);

    }
}


