#pragma checksum "D:\demo\test01\spark\ui\Spark.UI\MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "371984DCA045079E0D8AB821C25C9EC9C3E4BB3B8022AD51789539DAC284612B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.UI
{
    partial class MainWindow : 
        global::Microsoft.UI.Xaml.Window, 
        global::Microsoft.UI.Xaml.Markup.IComponentConnector
    {

        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 2: // MainWindow.xaml line 16
                {
                    this.Root = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 4: // MainWindow.xaml line 497
                {
                    global::Microsoft.UI.Xaml.Controls.Button element4 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element4).Click += this.OnInstallFromMarketplace;
                    ((global::Microsoft.UI.Xaml.Controls.Button)element4).Loaded += this.OnInstallButtonLoaded;
                    ((global::Microsoft.UI.Xaml.Controls.Button)element4).Unloaded += this.OnInstallButtonUnloaded;
                    ((global::Microsoft.UI.Xaml.Controls.Button)element4).DataContextChanged += this.OnInstallButtonDataContextChanged;
                }
                break;
            case 69: // MainWindow.xaml line 564
                {
                    this.ContentClip = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 70: // MainWindow.xaml line 567
                {
                    this.MainPanel = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 71: // MainWindow.xaml line 892
                {
                    this.SettingsPanel = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Grid)this.SettingsPanel).KeyDown += this.OnSettingsKeyDown;
                }
                break;
            case 72: // MainWindow.xaml line 1858
                {
                    this.FavGroupPanel = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Grid)this.FavGroupPanel).Tapped += this.OnFavGroupScrimTapped;
                }
                break;
            case 73: // MainWindow.xaml line 1896
                {
                    this.FavConfirmPanel = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Grid)this.FavConfirmPanel).KeyDown += this.OnFavConfirmKeyDown;
                    ((global::Microsoft.UI.Xaml.Controls.Grid)this.FavConfirmPanel).Tapped += this.OnFavConfirmScrimTapped;
                }
                break;
            case 74: // MainWindow.xaml line 1898
                {
                    this.FavConfirmCard = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Border>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Border)this.FavConfirmCard).Tapped += this.OnFavConfirmCardTapped;
                }
                break;
            case 75: // MainWindow.xaml line 1903
                {
                    this.FavConfirmCardShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 76: // MainWindow.xaml line 1904
                {
                    this.FavConfirmCardScale = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.ScaleTransform>(target);
                }
                break;
            case 77: // MainWindow.xaml line 1910
                {
                    this.FavConfirmMsg = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 78: // MainWindow.xaml line 1913
                {
                    this.FavConfirmCancelBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.FavConfirmCancelBtn).Click += this.OnFavConfirmCancel;
                }
                break;
            case 79: // MainWindow.xaml line 1917
                {
                    global::Microsoft.UI.Xaml.Controls.Button element79 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element79).Click += this.OnFavConfirmDelete;
                }
                break;
            case 80: // MainWindow.xaml line 1860
                {
                    this.FavGroupCard = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Border>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Border)this.FavGroupCard).Tapped += this.OnFavGroupCardTapped;
                }
                break;
            case 81: // MainWindow.xaml line 1866
                {
                    this.FavGroupCardShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 82: // MainWindow.xaml line 1867
                {
                    this.FavGroupCardScale = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.ScaleTransform>(target);
                }
                break;
            case 83: // MainWindow.xaml line 1873
                {
                    this.FavGroupName = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.TextBox)this.FavGroupName).KeyDown += this.OnFavGroupNameKeyDown;
                }
                break;
            case 84: // MainWindow.xaml line 1882
                {
                    global::Microsoft.UI.Xaml.Controls.Button element84 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element84).Click += this.OnFavGroupCancel;
                }
                break;
            case 85: // MainWindow.xaml line 1886
                {
                    global::Microsoft.UI.Xaml.Controls.Button element85 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element85).Click += this.OnFavGroupCreate;
                }
                break;
            case 86: // MainWindow.xaml line 897
                {
                    this.SetShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 87: // MainWindow.xaml line 898
                {
                    this.SetScale = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.ScaleTransform>(target);
                }
                break;
            case 88: // MainWindow.xaml line 980
                {
                    this.PaneGeneral = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 89: // MainWindow.xaml line 1046
                {
                    this.PaneAppearance = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 90: // MainWindow.xaml line 1082
                {
                    this.PaneBuiltins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 91: // MainWindow.xaml line 1162
                {
                    this.PanePlugins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 92: // MainWindow.xaml line 1793
                {
                    this.PaneAbout = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 93: // MainWindow.xaml line 1795
                {
                    this.PaneAboutShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 94: // MainWindow.xaml line 1838
                {
                    this.AboutUpdateStatus = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 95: // MainWindow.xaml line 1840
                {
                    this.UpdateProgress = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ProgressBar>(target);
                }
                break;
            case 96: // MainWindow.xaml line 1823
                {
                    this.BtnCheckUpdate = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnCheckUpdate).Click += this.OnCheckUpdate;
                }
                break;
            case 97: // MainWindow.xaml line 1830
                {
                    this.BtnOpenRelease = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnOpenRelease).Click += this.OnOpenRelease;
                }
                break;
            case 98: // MainWindow.xaml line 1835
                {
                    global::Microsoft.UI.Xaml.Controls.Button element98 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element98).Click += this.OnOpenGithub;
                }
                break;
            case 99: // MainWindow.xaml line 1827
                {
                    this.CheckUpdateLabel = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 100: // MainWindow.xaml line 1810
                {
                    this.AboutVersionText = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 101: // MainWindow.xaml line 1164
                {
                    this.PanePluginsShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 102: // MainWindow.xaml line 1188
                {
                    this.SubPaneInstalledPlugins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 103: // MainWindow.xaml line 1475
                {
                    this.SubPanePluginSecurity = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 104: // MainWindow.xaml line 1572
                {
                    this.SubPaneMarketplace = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 105: // MainWindow.xaml line 1575
                {
                    this.SubPaneMarketplaceShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 106: // MainWindow.xaml line 1652
                {
                    this.MarketFilterRow = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 107: // MainWindow.xaml line 1679
                {
                    this.MarketUpdateNotice = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Border>(target);
                }
                break;
            case 108: // MainWindow.xaml line 1706
                {
                    this.MarketTagScroll = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ScrollViewer>(target);
                }
                break;
            case 109: // MainWindow.xaml line 1729
                {
                    this.MarketLoadingWrap = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 110: // MainWindow.xaml line 1736
                {
                    this.MarketStatusText = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 111: // MainWindow.xaml line 1741
                {
                    this.MarketEmpty = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 112: // MainWindow.xaml line 1753
                {
                    this.MarketFilterEmpty = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 113: // MainWindow.xaml line 1758
                {
                    this.MarketList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ListView>(target);
                }
                break;
            case 116: // MainWindow.xaml line 1710
                {
                    this.MarketTagBar = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ItemsControl>(target);
                }
                break;
            case 117: // MainWindow.xaml line 1718
                {
                    global::Microsoft.UI.Xaml.Controls.Button element117 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element117).Click += this.OnMarketTagClick;
                }
                break;
            case 118: // MainWindow.xaml line 1694
                {
                    this.MarketUpdateAllBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.MarketUpdateAllBtn).Click += this.OnUpdateAllMarket;
                }
                break;
            case 119: // MainWindow.xaml line 1690
                {
                    this.MarketUpdateNoticeText = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 120: // MainWindow.xaml line 1657
                {
                    this.MarketFilterBox = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.TextBox)this.MarketFilterBox).TextChanged += this.OnMarketFilterChanged;
                }
                break;
            case 121: // MainWindow.xaml line 1662
                {
                    this.MarketFilterCombo = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ComboBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.ComboBox)this.MarketFilterCombo).SelectionChanged += this.OnMarketFilterChanged;
                }
                break;
            case 122: // MainWindow.xaml line 1605
                {
                    this.MarketCustomReposPanel = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 123: // MainWindow.xaml line 1640
                {
                    this.MarketCustomWarning = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Border>(target);
                }
                break;
            case 124: // MainWindow.xaml line 1607
                {
                    this.MarketCustomUrlList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ItemsControl>(target);
                }
                break;
            case 125: // MainWindow.xaml line 1628
                {
                    global::Microsoft.UI.Xaml.Controls.Button element125 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element125).Click += this.OnAddCustomRepoUrl;
                }
                break;
            case 126: // MainWindow.xaml line 1632
                {
                    global::Microsoft.UI.Xaml.Controls.Button element126 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element126).Click += this.OnSaveCustomRepoUrls;
                }
                break;
            case 128: // MainWindow.xaml line 1617
                {
                    global::Microsoft.UI.Xaml.Controls.Button element128 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element128).Click += this.OnRemoveCustomRepoUrl;
                }
                break;
            case 129: // MainWindow.xaml line 1587
                {
                    this.MarketSourceCombo = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ComboBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.ComboBox)this.MarketSourceCombo).SelectionChanged += this.OnMarketSourceChanged;
                }
                break;
            case 130: // MainWindow.xaml line 1589
                {
                    this.MarketCustomManageBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.MarketCustomManageBtn).Click += this.OnToggleManageCustomRepos;
                }
                break;
            case 131: // MainWindow.xaml line 1593
                {
                    this.MarketRefreshBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.MarketRefreshBtn).Click += this.OnMarketRefresh;
                }
                break;
            case 132: // MainWindow.xaml line 1478
                {
                    this.SubPanePluginSecurityShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 133: // MainWindow.xaml line 1511
                {
                    this.TrustedDevList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ItemsControl>(target);
                }
                break;
            case 134: // MainWindow.xaml line 1565
                {
                    this.TrustedDevStatus = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 135: // MainWindow.xaml line 1550
                {
                    this.TrustedDevKeyId = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBox>(target);
                }
                break;
            case 136: // MainWindow.xaml line 1554
                {
                    this.TrustedDevPubkey = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBox>(target);
                }
                break;
            case 137: // MainWindow.xaml line 1558
                {
                    global::Microsoft.UI.Xaml.Controls.Button element137 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element137).Click += this.OnAddTrustedDev;
                }
                break;
            case 139: // MainWindow.xaml line 1530
                {
                    global::Microsoft.UI.Xaml.Controls.Button element139 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element139).Click += this.OnRemoveTrustedDev;
                }
                break;
            case 140: // MainWindow.xaml line 1494
                {
                    this.StrictModeSwitch = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.StrictModeSwitch).Checked += this.OnToggleStrictMode;
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.StrictModeSwitch).Unchecked += this.OnToggleStrictMode;
                }
                break;
            case 141: // MainWindow.xaml line 1191
                {
                    this.SubPaneInstalledPluginsShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 142: // MainWindow.xaml line 1259
                {
                    this.PluginStatus = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 143: // MainWindow.xaml line 1264
                {
                    this.PluginEmpty = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 144: // MainWindow.xaml line 1275
                {
                    this.PluginList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ListView>(target);
                    ((global::Microsoft.UI.Xaml.Controls.ListView)this.PluginList).ContainerContentChanging += this.OnPluginItemRealized;
                }
                break;
            case 150: // MainWindow.xaml line 1438
                {
                    global::Microsoft.UI.Xaml.Controls.Button element150 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element150).Click += this.OnOpenPluginPage;
                }
                break;
            case 151: // MainWindow.xaml line 1447
                {
                    global::Microsoft.UI.Xaml.Controls.Button element151 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element151).Click += this.OnDebugPlugin;
                }
                break;
            case 152: // MainWindow.xaml line 1456
                {
                    global::Microsoft.UI.Xaml.Controls.Button element152 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element152).Click += this.OnUninstallPlugin;
                }
                break;
            case 154: // MainWindow.xaml line 1417
                {
                    global::Microsoft.UI.Xaml.Controls.CheckBox element154 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.CheckBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.CheckBox)element154).Checked += this.OnPermissionToggled;
                    ((global::Microsoft.UI.Xaml.Controls.CheckBox)element154).Unchecked += this.OnPermissionToggled;
                }
                break;
            case 155: // MainWindow.xaml line 1422
                {
                    global::Microsoft.UI.Xaml.Controls.Button element155 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element155).Click += this.OnFsScopeEdit;
                }
                break;
            case 157: // MainWindow.xaml line 1355
                {
                    global::Microsoft.UI.Xaml.Controls.Button element157 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element157).Click += this.OnTogglePluginExpand;
                }
                break;
            case 158: // MainWindow.xaml line 1366
                {
                    global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton element158 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)element158).Checked += this.OnPluginToggled;
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)element158).Unchecked += this.OnPluginToggled;
                }
                break;
            case 160: // MainWindow.xaml line 1249
                {
                    this.ChangePluginDirWrap = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 161: // MainWindow.xaml line 1250
                {
                    this.ChangePluginDirBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.ChangePluginDirBtn).Click += this.OnChangePluginDir;
                }
                break;
            case 162: // MainWindow.xaml line 1246
                {
                    this.PluginDirText = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 163: // MainWindow.xaml line 1198
                {
                    global::Microsoft.UI.Xaml.Controls.Button element163 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element163).Click += this.OnInstallPlugin;
                }
                break;
            case 164: // MainWindow.xaml line 1209
                {
                    global::Microsoft.UI.Xaml.Controls.Button element164 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element164).Click += this.OnInstallSparkPluginFile;
                }
                break;
            case 165: // MainWindow.xaml line 1218
                {
                    this.DevLoadPluginWrap = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 166: // MainWindow.xaml line 1229
                {
                    global::Microsoft.UI.Xaml.Controls.Button element166 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element166).Click += this.OnRefreshPlugins;
                }
                break;
            case 167: // MainWindow.xaml line 1219
                {
                    this.DevLoadPluginBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.DevLoadPluginBtn).Click += this.OnDevLoadPlugin;
                }
                break;
            case 168: // MainWindow.xaml line 1171
                {
                    this.TabInstalledPluginsBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.TabInstalledPluginsBtn).Click += this.OnSelectInstalledPluginsTab;
                }
                break;
            case 169: // MainWindow.xaml line 1176
                {
                    this.TabPluginSecurityBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.TabPluginSecurityBtn).Click += this.OnSelectPluginSecurityTab;
                }
                break;
            case 170: // MainWindow.xaml line 1180
                {
                    this.TabMarketplaceBtn = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.TabMarketplaceBtn).Click += this.OnSelectMarketplaceTab;
                }
                break;
            case 171: // MainWindow.xaml line 1084
                {
                    this.PaneBuiltinsShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 172: // MainWindow.xaml line 1087
                {
                    this.BuiltinFilterBox = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.TextBox)this.BuiltinFilterBox).TextChanged += this.OnBuiltinFilterChanged;
                }
                break;
            case 173: // MainWindow.xaml line 1092
                {
                    this.BuiltinList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ListView>(target);
                }
                break;
            case 174: // MainWindow.xaml line 1156
                {
                    this.BuiltinFilterEmpty = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 177: // MainWindow.xaml line 1048
                {
                    this.PaneAppearanceShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 178: // MainWindow.xaml line 1072
                {
                    this.ViewCombo = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ComboBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.ComboBox)this.ViewCombo).SelectionChanged += this.OnViewChanged;
                }
                break;
            case 179: // MainWindow.xaml line 1057
                {
                    this.ThemeCombo = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ComboBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.ComboBox)this.ThemeCombo).SelectionChanged += this.OnThemeChanged;
                }
                break;
            case 180: // MainWindow.xaml line 983
                {
                    this.PaneGeneralShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 181: // MainWindow.xaml line 1040
                {
                    this.DevModeSwitch = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.DevModeSwitch).Checked += this.OnToggleDevMode;
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.DevModeSwitch).Unchecked += this.OnToggleDevMode;
                }
                break;
            case 182: // MainWindow.xaml line 1027
                {
                    this.BallSwitch = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.BallSwitch).Checked += this.OnToggleBall;
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.BallSwitch).Unchecked += this.OnToggleBall;
                }
                break;
            case 183: // MainWindow.xaml line 1010
                {
                    this.BtnHotkeyAlt = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnHotkeyAlt).Click += this.OnHotkeyPreset;
                }
                break;
            case 184: // MainWindow.xaml line 1012
                {
                    this.BtnHotkeyCtrl = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnHotkeyCtrl).Click += this.OnHotkeyPreset;
                }
                break;
            case 185: // MainWindow.xaml line 995
                {
                    this.StartupSwitch = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.StartupSwitch).Checked += this.OnToggleStartup;
                    ((global::Microsoft.UI.Xaml.Controls.Primitives.ToggleButton)this.StartupSwitch).Unchecked += this.OnToggleStartup;
                }
                break;
            case 186: // MainWindow.xaml line 942
                {
                    this.NavGeneral = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.NavGeneral).Click += this.OnSettingsNav;
                }
                break;
            case 187: // MainWindow.xaml line 948
                {
                    this.NavAppearance = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.NavAppearance).Click += this.OnSettingsNav;
                }
                break;
            case 188: // MainWindow.xaml line 954
                {
                    this.NavBuiltins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.NavBuiltins).Click += this.OnSettingsNav;
                }
                break;
            case 189: // MainWindow.xaml line 960
                {
                    this.NavPlugins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.NavPlugins).Click += this.OnSettingsNav;
                }
                break;
            case 190: // MainWindow.xaml line 966
                {
                    this.NavAbout = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.NavAbout).Click += this.OnSettingsNav;
                }
                break;
            case 191: // MainWindow.xaml line 968
                {
                    this.NavIconAbout = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.FontIcon>(target);
                }
                break;
            case 192: // MainWindow.xaml line 962
                {
                    this.NavIconPlugins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.FontIcon>(target);
                }
                break;
            case 193: // MainWindow.xaml line 956
                {
                    this.NavIconBuiltins = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.FontIcon>(target);
                }
                break;
            case 194: // MainWindow.xaml line 950
                {
                    this.NavIconAppearance = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.FontIcon>(target);
                }
                break;
            case 195: // MainWindow.xaml line 944
                {
                    this.NavIconGeneral = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.FontIcon>(target);
                }
                break;
            case 196: // MainWindow.xaml line 913
                {
                    global::Microsoft.UI.Xaml.Controls.Button element196 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)element196).Click += this.OnCloseSettings;
                }
                break;
            case 197: // MainWindow.xaml line 571
                {
                    this.MainShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 198: // MainWindow.xaml line 572
                {
                    this.MainScale = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.ScaleTransform>(target);
                }
                break;
            case 199: // MainWindow.xaml line 649
                {
                    this.ResultList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ListView>(target);
                    ((global::Microsoft.UI.Xaml.Controls.ListView)this.ResultList).ItemClick += this.OnItemClick;
                }
                break;
            case 200: // MainWindow.xaml line 698
                {
                    this.ResultGrid = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.GridView>(target);
                    ((global::Microsoft.UI.Xaml.Controls.GridView)this.ResultGrid).ItemClick += this.OnItemClick;
                }
                break;
            case 201: // MainWindow.xaml line 793
                {
                    this.EmptyState = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 202: // MainWindow.xaml line 873
                {
                    this.FooterBar = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Grid>(target);
                }
                break;
            case 203: // MainWindow.xaml line 886
                {
                    this.Footer = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 204: // MainWindow.xaml line 803
                {
                    this.FavRoot = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 205: // MainWindow.xaml line 853
                {
                    this.FavBodyClip = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Border>(target);
                }
                break;
            case 206: // MainWindow.xaml line 855
                {
                    this.FavBodyClipRect = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.RectangleGeometry>(target);
                }
                break;
            case 207: // MainWindow.xaml line 857
                {
                    this.FavBody = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ScrollViewer>(target);
                }
                break;
            case 208: // MainWindow.xaml line 860
                {
                    this.FavItems = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 209: // MainWindow.xaml line 864
                {
                    this.FavItemsShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 210: // MainWindow.xaml line 807
                {
                    this.FavGroupsCol = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.ColumnDefinition>(target);
                }
                break;
            case 211: // MainWindow.xaml line 811
                {
                    this.FavToggle = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.FavToggle).Click += this.OnFavToggle;
                }
                break;
            case 212: // MainWindow.xaml line 839
                {
                    this.FavAddGroup = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.FavAddGroup).Click += this.OnFavAddGroup;
                }
                break;
            case 213: // MainWindow.xaml line 836
                {
                    this.FavGroups = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.StackPanel>(target);
                }
                break;
            case 214: // MainWindow.xaml line 814
                {
                    this.FavChevronPath = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Shapes.Path>(target);
                }
                break;
            case 215: // MainWindow.xaml line 829
                {
                    this.FavCount = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 216: // MainWindow.xaml line 820
                {
                    this.FavChevronShift = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.TranslateTransform>(target);
                }
                break;
            case 217: // MainWindow.xaml line 821
                {
                    this.FavChevronRotate = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Media.RotateTransform>(target);
                }
                break;
            case 230: // MainWindow.xaml line 783
                {
                    global::Microsoft.UI.Xaml.Controls.TextBlock element230 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                    ((global::Microsoft.UI.Xaml.Controls.TextBlock)element230).DataContextChanged += this.OnTitleDataContextChanged;
                }
                break;
            case 232: // MainWindow.xaml line 681
                {
                    global::Microsoft.UI.Xaml.Controls.TextBlock element232 = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                    ((global::Microsoft.UI.Xaml.Controls.TextBlock)element232).DataContextChanged += this.OnTitleDataContextChanged;
                }
                break;
            case 233: // MainWindow.xaml line 600
                {
                    this.QueryBox = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBox>(target);
                    ((global::Microsoft.UI.Xaml.Controls.TextBox)this.QueryBox).TextChanged += this.OnQueryChanged;
                    ((global::Microsoft.UI.Xaml.Controls.TextBox)this.QueryBox).KeyDown += this.OnQueryKeyDown;
                }
                break;
            case 234: // MainWindow.xaml line 610
                {
                    this.SearchMeta = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.TextBlock>(target);
                }
                break;
            case 235: // MainWindow.xaml line 635
                {
                    this.BtnSettings = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnSettings).Click += this.OnOpenSettings;
                }
                break;
            case 236: // MainWindow.xaml line 617
                {
                    this.BtnViewList = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnViewList).Click += this.OnViewList;
                }
                break;
            case 237: // MainWindow.xaml line 624
                {
                    this.BtnViewGrid = global::WinRT.CastExtensions.As<global::Microsoft.UI.Xaml.Controls.Button>(target);
                    ((global::Microsoft.UI.Xaml.Controls.Button)this.BtnViewGrid).Click += this.OnViewGrid;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }


        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 3.0.0.2501")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Microsoft.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

