//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Spark")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.2.13.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.2.13+843e92ddc53356494666c6450e00b22728dfef0b")]
[assembly: System.Reflection.AssemblyProductAttribute("Spark")]
[assembly: System.Reflection.AssemblyTitleAttribute("Spark")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.2.13.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows10.0.19041.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows10.0.17763.0")]

// 由 MSBuild WriteCodeFragment 类生成。

